name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: autogen
      run: ./autogen.sh
    - name: add repo
      run: sudo add-apt-repository ppa:bitcoin/bitcoin
    - name: update repo
      run: sudo apt-get update
    - name: install deps db
      run: sudo apt-get install libdb4.8-dev libdb4.8++-dev
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
