name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: cd depends
      run: cd depends
    - name: make HOST=x86_64-w64-mingw32
      run: make HOST=x86_64-w64-mingw32
    - name: cd ..
      run: cd ..
    - name: ./autogen.sh
      run: ./autogen.sh
    - name: ./configure --prefix=$PWD/depends/x86_64-w64-mingw32
      run: ./configure --prefix=$PWD/depends/x86_64-w64-mingw32
    - name: make
      run: make
    - name: make check
      run: make check
